SELECT A.CATEGORY, MAX_PRICE, A.PRODUCT_NAME
FROM FOOD_PRODUCT A
JOIN 
(
    SELECT CATEGORY, MAX(PRICE) 'MAX_PRICE'
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) B ON A.PRICE = B.MAX_PRICE
WHERE A.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY MAX_PRICE DESC
