SELECT PRODUCT_ID, PRODUCT_NAME, SUM(PRICE * AMOUNT) 'TOTAL_SALES'
FROM
(
    SELECT A.PRODUCT_ID, PRODUCT_NAME, PRICE, AMOUNT
    FROM FOOD_PRODUCT A
    JOIN FOOD_ORDER B ON A.PRODUCT_ID = B.PRODUCT_ID
    WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
) C
GROUP BY PRODUCT_ID, PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID
