SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') 'REVIEW_DATE'
FROM MEMBER_PROFILE F
JOIN REST_REVIEW G ON F.MEMBER_ID = G.MEMBER_ID
WHERE MEMBER_NAME IN(
    SELECT MEMBER_NAME
    FROM MEMBER_PROFILE D
    JOIN REST_REVIEW E ON D.MEMBER_ID = E.MEMBER_ID
    GROUP BY D.MEMBER_ID
    HAVING COUNT(*) = (
        SELECT MAX(C.CNT)
        FROM
        (
            SELECT COUNT(*) 'CNT'
            FROM MEMBER_PROFILE A
            JOIN REST_REVIEW B ON A.MEMBER_ID = B.MEMBER_ID
            GROUP BY A.MEMBER_ID
        ) C
    )
)
ORDER BY REVIEW_DATE, REVIEW_TEXT
