SELECT APNT_NO, A.PT_NAME, A.PT_NO, B.MCDP_CD, DR_NAME, APNT_YMD
FROM (
    PATIENT A
    JOIN APPOINTMENT B ON A.PT_NO = B.PT_NO
)
JOIN DOCTOR C ON B.MDDR_ID = C.DR_ID
WHERE DATE_FORMAT(APNT_YMD, '%Y-%m-%d') = '2022-04-13' AND
    APNT_CNCL_YN = 'N' AND
    B.MCDP_CD = 'CS'
ORDER BY APNT_YMD
