SELECT A.ID, A.NAME, A.HOST_ID
FROM PLACES A
JOIN (
        SELECT B.HOST_ID, COUNT(B.ID)
        FROM PLACES B
        GROUP BY B.HOST_ID
        HAVING COUNT(B.ID) >= 2) C
ON A.HOST_ID = C.HOST_ID
ORDER BY A.ID
