SELECT A.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2) 'SCORE'
FROM REST_INFO A
JOIN REST_REVIEW B ON A.REST_ID = B.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY 1,2,3,4,5
ORDER BY SCORE DESC, FAVORITES DESC
