SELECT A.CART_ID
FROM (
    SELECT CART_ID, GROUP_CONCAT(DISTINCT NAME) 'PURCHASE'
    FROM CART_PRODUCTS
    WHERE NAME IN ('Milk', 'Yogurt')
    GROUP BY CART_ID
    HAVING PURCHASE = 'Milk,Yogurt'
) A
