SELECT MONTH(START_DATE) 'MONTH', CAR_ID, COUNT(*) 'RECORDS'
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE <= '2022-10-31' AND START_DATE >= '2022-08-01' AND 
    CAR_ID IN(SELECT CAR_ID
              FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
              WHERE START_DATE <= '2022-10-31' AND START_DATE >= '2022-08-01'
              GROUP BY CAR_ID
              HAVING COUNT(CAR_ID) >= 5)
GROUP BY 1, 2
HAVING RECORDS >= 1
ORDER BY 1, 2 DESC
